{{- define "common.canary.tpl" -}}
{{- $username := (split "_" $.Chart.Name)._0 }}
{{- $appName := (split "_" $.Chart.Name)._1 }}
{{- $appValues := index $.Values $username $appName }}
apiVersion: flagger.app/v1beta1
kind: Canary
{{ include "common.metadataCustom" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  progressDeadlineSeconds: 60
{{- if $appValues.hpa }}
  autoscalerRef:
    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    name: {{ .Chart.Name }}
{{- end }}
  service:
    port: 80
    portName: http
    targetPort: 80
    gateways:
    - {{ .Chart.Name }}.istio-system.svc.cluster.local
    hosts:
    - {{ .Values.baseDomain.name }}
    trafficPolicy:
      loadBalancer:
        simple: LEAST_CONN
    match:
      - uri:
          prefix: /{{ $username }}/{{ $appName }}
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    interval: 1m
    maxWeight: 100
    metrics:
    - interval: 1m
      name: request-success-rate
      thresholdRange:
        min: 1
    stepWeight: 10
    threshold: 10
    webhooks:
    - name: rollback gate
      timeout: 30s
      type: rollback
      url: http://172.31.31.114:8888/rollback
{{- end }}
{{- define "common.canary" -}}
{{- template "common.util.merge" (append . "common.canary.tpl") -}}
{{- end -}}
