{{- define "common.secret.tpl" -}}
apiVersion: v1
kind: Secret
{{ include "common.metadataCustom" . }}
type: Opaque
data: {}
{{- end -}}
{{- define "common.secret" -}}
{{- template "common.util.merge" (append . "common.secret.tpl") -}}
{{- end -}}
